version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DEV_PORT_WEB:-3001}:3000
    volumes:
      - ./:/workspaces/app
    working_dir: /workspaces/app
    tty: true
    environment:
      - TZ=${TZ:-}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=public&connect_timeout=10
      - ALLOW_ORIGIN=${ALLOW_ORIGIN:-http://localhost:3000}
      - KEY_PATH=${KEY_PATH:-0123456789abcdef}
      - PEPPER_PATH=${PEPPER_PATH:-dummy}
  db:
    image: postgres:15.4-bullseye
    ports:
      - ${DEV_PORT_DB:-15432}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - TZ=${TZ:-}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db:
    driver: local
