version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/app
    working_dir: /workspaces/app
    tty: true
    environment:
      - TZ=${TZ:-}
