version: "3"
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/app
    working_dir: /workspaces/app
    tty: true
    environment:
      - TZ=${TZ:-}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=public&connect_timeout=10
      - ALLOW_ORIGIN=${ALLOW_ORIGIN:-http://localhost:3000}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-jwt}
      - JWT_EXPIRE_HOUR=${JWT_EXPIRE_HOUR:-1}
      - PEPPER_PASSWORD=${PEPPER_PASSWORD:-dummy}
      - KEY_PATH=${KEY_PATH:-0123456789abcdef}
      - PEPPER_PATH=${PEPPER_PATH:-dummy}

  http:
    <<: *app
    ports:
      - ${DEV_PORT_WEB:-3001}:3000
    working_dir: /workspaces/app/interfaces/http
    command: air -c .air.toml

  db:
    image: postgres:15.4-bullseye
    ports:
      - ${DEV_PORT_DB:-15432}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - TZ=${TZ:-}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db:
    driver: local
